const SET_SCREEN_NUMBER = 'SET_SCREEN_NUMBER';
const SET_FIGHTERS = 'SET_FIGHTERS';
const SET_SELECTED = 'SET_SELECTED';
const SET_BONUS_CODE = 'SET_BONUS_CODE';
const SET_BONUS_STATUS = 'SET_BONUS_STATUS';

const actionTypes = {
  SET_SCREEN_NUMBER,
  SET_FIGHTERS,
  SET_SELECTED,
  SET_BONUS_CODE,
  SET_BONUS_STATUS,
};

export default actionTypes